import type { Metadata } from "next";
import { Geist, Geist_Mono, Imprima } from "next/font/google"; // Import Imprima
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const imprima = Imprima({
  variable: "--font-imprima",
  subsets: ["latin"],
  weight: ["400"], // Only 400 is available
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${imprima.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
